### ISSUE TITLE
Some non-optional fields are listed as optional

### ISSUE THREAD

**Issue by sreichar** [kubevirt/api-reference#15]
Most top level objects have kind and apiVersion listed as optional.  

Actually they typically list all fields as optional.   

With required fields being listed as optional, not sure which fields are really required.

**Comment by rmohr** [comment]
@sreichar let me try to improve the situation here. I have a few pending PRs regarding to that topic. I am not sure I can provide a solution for listing `kind` and `apiVersion` as optional, since it is also used in templates. Interestingly I see the same "mistake" in the api specification of k8s itself.
